# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('comprador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleHoja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Detalles',
            },
        ),
        migrations.CreateModel(
            name='Hoja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprador.Comprador')),
            ],
            options={
                'verbose_name_plural': 'Hojas',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_asignacion', models.DateField()),
                ('abierto', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.AddField(
            model_name='hoja',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.Libro'),
        ),
        migrations.AddField(
            model_name='detallehoja',
            name='hoja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.Hoja'),
        ),
    ]
